// This file is generated by rust-protobuf 2.18.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `udpa/annotations/versioning.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_1;

#[derive(PartialEq,Clone,Default)]
pub struct VersioningAnnotation {
    // message fields
    pub previous_message_type: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a VersioningAnnotation {
    fn default() -> &'a VersioningAnnotation {
        <VersioningAnnotation as ::protobuf::Message>::default_instance()
    }
}

impl VersioningAnnotation {
    pub fn new() -> VersioningAnnotation {
        ::std::default::Default::default()
    }

    // string previous_message_type = 1;


    pub fn get_previous_message_type(&self) -> &str {
        &self.previous_message_type
    }
    pub fn clear_previous_message_type(&mut self) {
        self.previous_message_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_previous_message_type(&mut self, v: ::std::string::String) {
        self.previous_message_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_previous_message_type(&mut self) -> &mut ::std::string::String {
        &mut self.previous_message_type
    }

    // Take field
    pub fn take_previous_message_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.previous_message_type, ::std::string::String::new())
    }
}

impl ::protobuf::Message for VersioningAnnotation {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.previous_message_type)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.previous_message_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.previous_message_type);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.previous_message_type.is_empty() {
            os.write_string(1, &self.previous_message_type)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VersioningAnnotation {
        VersioningAnnotation::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "previous_message_type",
                |m: &VersioningAnnotation| { &m.previous_message_type },
                |m: &mut VersioningAnnotation| { &mut m.previous_message_type },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<VersioningAnnotation>(
                "VersioningAnnotation",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static VersioningAnnotation {
        static instance: ::protobuf::rt::LazyV2<VersioningAnnotation> = ::protobuf::rt::LazyV2::INIT;
        instance.get(VersioningAnnotation::new)
    }
}

impl ::protobuf::Clear for VersioningAnnotation {
    fn clear(&mut self) {
        self.previous_message_type.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VersioningAnnotation {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VersioningAnnotation {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

/// Extension fields
pub mod exts {

    pub const versioning: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeMessage<super::VersioningAnnotation>> = ::protobuf::ext::ExtFieldOptional { field_number: 7881811, phantom: ::std::marker::PhantomData };
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n!udpa/annotations/versioning.proto\x12\x10udpa.annotations\x1a\x20goog\
    le/protobuf/descriptor.proto\"J\n\x14VersioningAnnotation\x122\n\x15prev\
    ious_message_type\x18\x01\x20\x01(\tR\x13previousMessageType:j\n\nversio\
    ning\x18\xd3\x88\xe1\x03\x20\x01(\x0b2&.udpa.annotations.VersioningAnnot\
    ation\x12\x1f.google.protobuf.MessageOptionsR\nversioningb\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
