// This file is generated by rust-protobuf 2.18.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `envoy/config/filter/network/zookeeper_proxy/v1alpha1/zookeeper_proxy.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_1;

#[derive(PartialEq,Clone,Default)]
pub struct ZooKeeperProxy {
    // message fields
    pub stat_prefix: ::std::string::String,
    pub access_log: ::std::string::String,
    pub max_packet_bytes: ::protobuf::SingularPtrField<::protobuf::well_known_types::UInt32Value>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ZooKeeperProxy {
    fn default() -> &'a ZooKeeperProxy {
        <ZooKeeperProxy as ::protobuf::Message>::default_instance()
    }
}

impl ZooKeeperProxy {
    pub fn new() -> ZooKeeperProxy {
        ::std::default::Default::default()
    }

    // string stat_prefix = 1;


    pub fn get_stat_prefix(&self) -> &str {
        &self.stat_prefix
    }
    pub fn clear_stat_prefix(&mut self) {
        self.stat_prefix.clear();
    }

    // Param is passed by value, moved
    pub fn set_stat_prefix(&mut self, v: ::std::string::String) {
        self.stat_prefix = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_stat_prefix(&mut self) -> &mut ::std::string::String {
        &mut self.stat_prefix
    }

    // Take field
    pub fn take_stat_prefix(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.stat_prefix, ::std::string::String::new())
    }

    // string access_log = 2;


    pub fn get_access_log(&self) -> &str {
        &self.access_log
    }
    pub fn clear_access_log(&mut self) {
        self.access_log.clear();
    }

    // Param is passed by value, moved
    pub fn set_access_log(&mut self, v: ::std::string::String) {
        self.access_log = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_access_log(&mut self) -> &mut ::std::string::String {
        &mut self.access_log
    }

    // Take field
    pub fn take_access_log(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.access_log, ::std::string::String::new())
    }

    // .google.protobuf.UInt32Value max_packet_bytes = 3;


    pub fn get_max_packet_bytes(&self) -> &::protobuf::well_known_types::UInt32Value {
        self.max_packet_bytes.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::UInt32Value as ::protobuf::Message>::default_instance())
    }
    pub fn clear_max_packet_bytes(&mut self) {
        self.max_packet_bytes.clear();
    }

    pub fn has_max_packet_bytes(&self) -> bool {
        self.max_packet_bytes.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_packet_bytes(&mut self, v: ::protobuf::well_known_types::UInt32Value) {
        self.max_packet_bytes = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_max_packet_bytes(&mut self) -> &mut ::protobuf::well_known_types::UInt32Value {
        if self.max_packet_bytes.is_none() {
            self.max_packet_bytes.set_default();
        }
        self.max_packet_bytes.as_mut().unwrap()
    }

    // Take field
    pub fn take_max_packet_bytes(&mut self) -> ::protobuf::well_known_types::UInt32Value {
        self.max_packet_bytes.take().unwrap_or_else(|| ::protobuf::well_known_types::UInt32Value::new())
    }
}

impl ::protobuf::Message for ZooKeeperProxy {
    fn is_initialized(&self) -> bool {
        for v in &self.max_packet_bytes {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.stat_prefix)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.access_log)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.max_packet_bytes)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.stat_prefix.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.stat_prefix);
        }
        if !self.access_log.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.access_log);
        }
        if let Some(ref v) = self.max_packet_bytes.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.stat_prefix.is_empty() {
            os.write_string(1, &self.stat_prefix)?;
        }
        if !self.access_log.is_empty() {
            os.write_string(2, &self.access_log)?;
        }
        if let Some(ref v) = self.max_packet_bytes.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ZooKeeperProxy {
        ZooKeeperProxy::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "stat_prefix",
                |m: &ZooKeeperProxy| { &m.stat_prefix },
                |m: &mut ZooKeeperProxy| { &mut m.stat_prefix },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "access_log",
                |m: &ZooKeeperProxy| { &m.access_log },
                |m: &mut ZooKeeperProxy| { &mut m.access_log },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::UInt32Value>>(
                "max_packet_bytes",
                |m: &ZooKeeperProxy| { &m.max_packet_bytes },
                |m: &mut ZooKeeperProxy| { &mut m.max_packet_bytes },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ZooKeeperProxy>(
                "ZooKeeperProxy",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ZooKeeperProxy {
        static instance: ::protobuf::rt::LazyV2<ZooKeeperProxy> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ZooKeeperProxy::new)
    }
}

impl ::protobuf::Clear for ZooKeeperProxy {
    fn clear(&mut self) {
        self.stat_prefix.clear();
        self.access_log.clear();
        self.max_packet_bytes.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ZooKeeperProxy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ZooKeeperProxy {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \nJenvoy/config/filter/network/zookeeper_proxy/v1alpha1/zookeeper_proxy.\
    proto\x124envoy.config.filter.network.zookeeper_proxy.v1alpha1\x1a\x1ego\
    ogle/protobuf/wrappers.proto\x1a\x1eudpa/annotations/migrate.proto\x1a\
    \x1dudpa/annotations/status.proto\x1a\x17validate/validate.proto\"\xa1\
    \x01\n\x0eZooKeeperProxy\x12(\n\x0bstat_prefix\x18\x01\x20\x01(\tR\nstat\
    PrefixB\x07\xfaB\x04r\x02\x20\x01\x12\x1d\n\naccess_log\x18\x02\x20\x01(\
    \tR\taccessLog\x12F\n\x10max_packet_bytes\x18\x03\x20\x01(\x0b2\x1c.goog\
    le.protobuf.UInt32ValueR\x0emaxPacketBytesB\x9e\x01\nBio.envoyproxy.envo\
    y.config.filter.network.zookeeper_proxy.v1alpha1B\x13ZookeeperProxyProto\
    P\x01\xba\x80\xc8\xd1\x06\x02\x10\x01\xf2\x98\xfe\x8f\x055\x123envoy.ext\
    ensions.filters.network.zookeeper_proxy.v3b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
